
[site]
url = "https://poetries.netlify.app"
name = "现代诗"
description = "你的思想，你的诗"
locale = "zh"
menu = [
  { name = "关于", url = "/about" },
  { name = "GitHub", url = "https://github.com/zineland/poetry" },
]


[theme]
primary_color = "#333"
article_extend_template = "templates/article-extend.html"

[authors]
daichang = { name = "戴畅", bio = "" }
qingqiu = { name = "陶清秋", bio = "业余作者。更多: tkzt.cn/n-notes/cheap-talks/cicadas-crying.html" }
zhuiguang = { name = "追光", bio = "无名的追光" }

[[issue]]
slug = "1"
number = 1
title = "第一季"
path = "content/issue-1"
